<a href="https://colab.research.google.com/github/ValentinKraravchenko/-Data-science-/blob/main/numpy%D0%9A%D1%80%D0%B0%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%BE_%D0%BB%D0%B0%D0%B12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Импортируйте пакет numpy под именем `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Создайте нулевой вектор размера 10 (★☆☆)

In [ ]:
some_list = np.zeros(10)
print(some_list)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Как узнать объем памяти любого массива (★☆☆)

In [ ]:

data = some_list.size * some_list.itemsize
print(data,"Байт(а)")


320 Байт(а)


#### 4. Создайте вектор со значениями от 10 до 49. (★☆☆)

In [ ]:
some_list=np.arange(10,50)
print(some_list)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 5. Создайте обратный вектор из вектора в задании 4 (первый элемент становится последним) (★☆☆)

In [ ]:
x=np.flipud(some_list)
print(x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 6. Создайте матрицу 3x3 со значениями от 0 до 8. (★☆☆)

In [ ]:
mass=np.arange(9).reshape(3,3)
print(mass)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 7. Найти индексы ненулевых элементов из [1,2,0,0,4,0 (★☆☆)

In [ ]:
mass= np.nonzero([1,2,0,0,4,0])
print(mass)

(array([0, 1, 4]),)


#### 8. Создайте массив 3x3x3 со случайными значениями (★☆☆)

In [ ]:
mass=np.random.random((3,3,3))
print(mass)

[[[0.18898025 0.88535402 0.34320942]
  [0.04254042 0.4511655  0.17973778]
  [0.98152959 0.07383157 0.38146709]]

 [[0.10499091 0.85635015 0.55522607]
  [0.05780791 0.06767045 0.22586713]
  [0.36494128 0.24188849 0.15444533]]

 [[0.82962427 0.56398388 0.96590181]
  [0.49317207 0.83771184 0.04003303]
  [0.09291608 0.72902913 0.91243619]]]


#### 9. Создайте массив 10x10 со случайными значениями и найдите минимальное и максимальное значения. (★☆☆)

In [ ]:
a=np.random.random((10,10))
Amin=a.min()
Amax=a.max()
print(a,"\n",Amin,Amax)

[[0.62767155 0.3599265  0.58471052 0.85941018 0.57416582 0.6286266
  0.82210509 0.40212109 0.56951949 0.45140928]
 [0.14949643 0.57235831 0.18893119 0.44214692 0.70637272 0.07526753
  0.15571825 0.05710354 0.38500847 0.24178374]
 [0.4557734  0.87495289 0.88252842 0.14571904 0.15153722 0.65189653
  0.2039432  0.86351828 0.28640375 0.76390136]
 [0.04557753 0.53956616 0.1359026  0.1001087  0.89691878 0.40773598
  0.68238025 0.61053077 0.02119116 0.37729945]
 [0.95685852 0.54288968 0.89018301 0.28183112 0.30057943 0.26919193
  0.8061447  0.18247694 0.12828674 0.58603603]
 [0.87738152 0.36033112 0.35837531 0.45760278 0.55883605 0.47600938
  0.75181012 0.96902668 0.74413175 0.40730576]
 [0.53809665 0.14687452 0.69164477 0.11671817 0.21475071 0.99880571
  0.84016041 0.10810876 0.0634406  0.60142528]
 [0.38328511 0.81120322 0.33815529 0.5617372  0.78620916 0.51108097
  0.92460263 0.96721218 0.01134382 0.54112659]
 [0.22009425 0.73777015 0.52872559 0.27078602 0.7613553  0.40823316
  0.15678039 

#### 10. Создайте случайный вектор размера 30 и найдите среднее значение(★☆☆)

In [ ]:
a = np.random.random(30)
x = a.mean()
print(x)

0.44949098050444614


#### 11. Создайте массив 2d 2x3 c 1 на границе и 0 внутри (★☆☆)

In [ ]:
###Думаю опечатка и надо 3х3
a = np.ones((3,3))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


#### 12. Каков результат следующего выражения? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 13. Рассмотрим массив размера (6,7,8). Каков индекс (x,y,z) 100-го элемента? (★☆☆)

In [ ]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 14. Умножить матрицу 5x3 на матрицу 3x2(★☆☆)

In [ ]:
a= np.dot(np.ones((5,3)), np.ones((3,2)))
print(a)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 15. Создайте одномерный массив со случайными значениями от 1 до 10, инвертируйте (поменяйте местами) все элементы, со значениями 3 и 8. (★☆☆)

In [ ]:
a = np.arange(11)
a[(3 <= a) & (a <= 8)] = np.flipud(a[(3 <= a) & (a <= 8)])
print(a)

[ 0  1  2  8  7  6  5  4  3  9 10]


#### 16. Каков результат следующих выражений? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-57-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-57-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 17. Как найти общие значения между двумя массивами? (★☆☆)

In [ ]:
A = np.random.randint(0,7,10)
print(A)
B = np.random.randint(0,10,10)
print(B)
x=np.intersect1d(A,B)
print(x)

[5 2 1 6 0 5 3 0 3 4]
[6 5 8 4 0 6 6 4 7 5]
[0 4 5 6]


#### 18. Как вычислить ((A+B)*(-A/2)) с заменой массива А (без копирования)? (★★☆)

In [ ]:
A = np.ones(3)*1
print('Исходный вектор A:\n', A)
B = np.ones(3)*2
print('Исходный вектор B:\n', B)
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(B,A,out=A)
print('Результат заданного выражения ((A+B)*(-A/2)) (без копирования):\n', A)

Исходный вектор A:
 [1. 1. 1.]
Исходный вектор B:
 [2. 2. 2.]
Результат заданного выражения ((A+B)*(-A/2)) (без копирования):
 [-1.5 -1.5 -1.5]


#### 19. Создайте матрицу 5x5 со значениями строк от 0 до 4. (★★☆)

In [ ]:
a = np.zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 20. Создайте вектор размера 10 со значениями в диапазоне от 0 до 1, исключая 1 и 0 (★★☆)

In [ ]:
a = np.linspace(0,1,12)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 21. Создайте случайный вектор размера 10 и отсортируйте его (★★☆)

In [ ]:
a = np.random.random(10)
a.sort()
print(a)

[0.1120969  0.15709086 0.18554342 0.23126845 0.36055349 0.37043785
 0.45538039 0.48337888 0.76165836 0.80126345]


#### 22. Можно ли суммировать небольшой массив быстрее, чем np.sum? (★★☆)

In [ ]:
a= np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
%%time
np.add.reduce(a)

CPU times: user 40 µs, sys: 6 µs, total: 46 µs
Wall time: 49.1 µs


45

In [ ]:
%%time
np.sum(a)

CPU times: user 63 µs, sys: 9 µs, total: 72 µs
Wall time: 77.2 µs


45

#### 23. Рассмотрим два случайных массива A и B, проверьте, равны ли они(★★☆)

In [ ]:
A = np.random.randint(0,3,10)
B = np.random.randint(0,3,10)
equal = np.allclose(A,B)
print(A,B)
print(equal)

[2 1 2 0 2 2 0 0 2 1] [0 1 2 2 1 0 1 1 0 1]
False


#### 24. Создайте случайный вектор размера 10 и замените максимальное значение на 0 (★★☆)

In [ ]:
a = np.random.random(10)
print(a)
a[a.argmax()] = 0
print(a)

[0.37132802 0.23681948 0.24980006 0.93701963 0.11053018 0.50570659
 0.57801928 0.92358356 0.57847782 0.77752703]
[0.37132802 0.23681948 0.24980006 0.         0.11053018 0.50570659
 0.57801928 0.92358356 0.57847782 0.77752703]


#### 25. Распечатайте минимальное и максимальное представимое значение для каждого скалярного типа numpy (★★☆)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 26. Как вывести все значения большого массива? (★★☆)

In [ ]:
print('Значение threshold по умолчанию:', np.get_printoptions()['threshold'])
Z = np.ones((26,40))
print('Вывод нулевого массива 26 на 40 с установками по дефолту:\n', Z)
np.set_printoptions(threshold=float("inf"))  # снять ограничения 
print('Вывод нулевого массива 26 на 40 без ограничений вывода:\n', Z)

Значение threshold по умолчанию: 1000
Вывод нулевого массива 26 на 40 с установками по дефолту:
 [[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Вывод нулевого массива 26 на 40 без ограничений вывода:
 [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 

#### 27. Рассмотрим случайный вектор формы (100,2), представляющий координаты, найдите расстояния между точками. (★★☆)

In [ ]:
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.68831489 0.8514439  0.87614363 0.60653845 0.76390023
  0.44908928 0.43761538 0.37121572 0.75054929]
 [0.68831489 0.         0.18001949 0.56267351 0.10105291 0.07730927
  0.23922617 0.40613242 0.44800491 0.52260007]
 [0.8514439  0.18001949 0.         0.50905144 0.24496597 0.13158029
  0.40694048 0.50929201 0.56541297 0.51228298]
 [0.87614363 0.56267351 0.50905144 0.         0.51127843 0.58677758
  0.60452802 0.44343504 0.50609476 0.13003729]
 [0.60653845 0.10105291 0.24496597 0.51127843 0.         0.17552625
  0.16444893 0.30532355 0.34725559 0.45229612]
 [0.76390023 0.07730927 0.13158029 0.58677758 0.17552625 0.
  0.31510708 0.47774716 0.52251349 0.5625635 ]
 [0.44908928 0.23922617 0.40694048 0.60452802 0.16444893 0.31510708
  0.         0.25795142 0.26688406 0.5158684 ]
 [0.43761538 0.40613242 0.50929201 0.44343504 0.30532355 0.47774716
  0.25795142 0.         0.06894505 0.32418304]
 [0.37121572 0.44800491 0.56541297 0.50609476 0.34725559 0.52251349
  0.26688406 0.06894

#### 28. Как преобразовать массив с плавающей запятой (32 бита) в целое число (32 бита) с заменой?

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
print('Исходный вектор : \n', Z)
Y = Z.view(np.int32)  # создаем представление массива, но с другим типом
Y[:] = Z  # копируем в представление массива массив
print('Преобразованное представление массива Z = Y: \n',Y)

Исходный вектор : 
 [42.0199 62.4789 35.8671 57.0951 77.3062 28.0152 47.0523 27.3569 68.2671
  1.0083]
Преобразованное представление массива Z = Y: 
 [42 62 35 57 77 28 47 27 68  1]


#### 29. Создайте массив из следующего файла: (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from google.colab import files
uploaded = files.upload()


Saving primer.txt to primer.txt


In [ ]:
z = np.genfromtxt("primer.txt", delimiter=",")
print(z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 30. Вычтите среднее значение каждой строки случайной матрицы. (★★☆)

In [ ]:
a=np.random.randint(0,10,9).reshape(3,3)
b = a - a.mean(axis=1, keepdims=True)
print(a,"\n",b)

[[1 1 0]
 [1 6 5]
 [5 9 3]] 
 [[ 0.3333  0.3333 -0.6667]
 [-3.      2.      1.    ]
 [-0.6667  3.3333 -2.6667]]


#### 31. Рассмотрим случайный вектор, как добавить 1 к каждому элементу, индексированному вторым вектором (будьте осторожны с повторяющимися индексами)? (★★★)

In [ ]:
N = 10  # размер вектора

Z = np.ones(N)
print(f'Исходный вектор Z единичных значений длиной {N}:\n{Z}\nСумма элементов вектора Z: {sum(Z)}')
I = np.random.randint(1,N-1,N*3)
print(f'Вектор индексов I длиной {3*N} из случайных значений равномерно распределенных на полуинтервале [0,{N}):\n', I)
Z += np.bincount(I, minlength=len(Z))
print(f'Преобразованный вектор Z_:\n{Z}\nСумма элементов вектора Z_: {sum(Z)}')
print('Проверка выражения np.sum(Z_) = np.sum(Z) + len(I): ', np.sum(Z) == N + len(I))

Исходный вектор Z единичных значений длиной 10:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Сумма элементов вектора Z: 10.0
Вектор индексов I длиной 30 из случайных значений равномерно распределенных на полуинтервале [0,10):
 [3 2 6 3 8 5 7 8 5 5 1 7 8 2 6 1 7 4 1 7 3 5 3 3 6 4 3 1 1 6]
Преобразованный вектор Z_:
[1. 6. 3. 7. 3. 5. 5. 5. 4. 1.]
Сумма элементов вектора Z_: 40.0
Проверка выражения np.sum(Z_) = np.sum(Z) + len(I):  True


#### 32. Как перенести элементы вектора (X) в массив (F) на основе списка индексов (I)? (★★★)

In [ ]:
N = 20  # кол-во последних запросов к серверам
n = 15  # кол-во серверов

x = np.random.randint(1,5,N)
print(f'Исходный вектор Z с временем ответа серверов за последние {N} запросов (случайно):\n', x)
I = np.random.randint(1,n+1,N)
print(f'Вектор I с номерами серверов к которым были адресованны последние {N} запросов из вектора Z (случайно):\n', I)
F = np.bincount(I,weights=x)
print('Вектор Sum_Z_I с аккумулированным (просуммированным) временем ответа серверов из вектра Z по соответствующим серверам перечисленным в векторе I:\n', F[1:])


Исходный вектор Z с временем ответа серверов за последние 20 запросов (случайно):
 [2 1 4 3 1 4 4 4 2 1 4 2 4 2 2 4 4 4 4 2]
Вектор I с номерами серверов к которым были адресованны последние 20 запросов из вектора Z (случайно):
 [ 9  3  2 15  4  8 15 10  1  7  3 15 12 11 14 15  3 10  5  4]
Вектор Sum_Z_I с аккумулированным (просуммированным) временем ответа серверов из вектра Z по соответствующим серверам перечисленным в векторе I:
 [ 2.  4.  9.  3.  4.  0.  1.  4.  2.  8.  2.  4.  0.  2. 13.]


#### 33. Рассматривая четырехмерный массив, как получить сумму сразу (в одну операцию) по двум последним осям? (★★★)

In [ ]:
size_arr = (3,4,3,4)
Z = np.random.randint(0,2,size=size_arr)
sum_Z_last_two_axis_2 = Z.reshape(Z.shape[:-2] + (-1,)).sum(axis=-1)
print(Z)
print('Результат суммирования элементов вектора Z по двум последним осям другим способом:\n', sum_Z_last_two_axis_2)

[[[[0 1 0 1]
   [0 0 1 0]
   [1 0 1 1]]

  [[0 0 0 0]
   [1 1 1 1]
   [0 0 0 0]]

  [[1 1 0 0]
   [0 1 1 0]
   [1 0 0 1]]

  [[0 1 1 0]
   [1 1 1 1]
   [1 1 1 0]]]


 [[[1 1 1 1]
   [0 1 0 0]
   [0 0 0 1]]

  [[1 0 0 0]
   [0 1 1 0]
   [1 0 1 1]]

  [[0 0 1 1]
   [1 0 0 1]
   [1 0 1 0]]

  [[0 1 1 0]
   [0 1 0 0]
   [1 0 0 1]]]


 [[[0 1 1 0]
   [0 0 1 0]
   [0 1 1 1]]

  [[1 1 1 1]
   [0 0 1 1]
   [1 0 0 1]]

  [[1 0 0 0]
   [0 1 1 0]
   [0 1 1 1]]

  [[0 0 0 1]
   [1 0 1 0]
   [0 1 1 1]]]]
Результат суммирования элементов вектора Z по двум последним осям другим способом:
 [[6 4 6 9]
 [6 6 6 5]
 [6 8 6 6]]


#### 34. Рассмотрим вектор [1, 2, 3, 4, 5], как построить новый вектор с 3 последовательными нулями, чередующимися между каждым значением? (★★★)

In [ ]:
Z = np.array([1,2,3,4,5])
print(f'Исходный вектор Z длинной {len(Z)}:\n', Z)

nz = 3  # кол-во нулей между числами 
new_len_arr = len(Z) + (len(Z)-1)*(nz)  # новая длина вектора
Z0 = np.zeros(new_len_arr)
Z0[::nz+1] = Z  # вставляем в нулевой вектор значения вектора Z с шагом nz+1 
print(f'Итоговый вектор Z с тремя нулями между числами:\n', Z0)

Исходный вектор Z длинной 5:
 [1 2 3 4 5]
Итоговый вектор Z с тремя нулями между числами:
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 35. Рассмотрим массив размерности (5,5,3), как его умножить на массив размерностью (5,5)? (★★★)

In [ ]:
A = np.arange(5*5*3).reshape(5,5,3)
print(f'Трех мерный массив A размером (5,5,3):\n', A)
B = 0.1*np.ones((5,5))
print(f'Двумерный массив B размером (5,5):\n', B)
print(f'Результат перемножения массивов A и B:\n',A * B[:,:,None])

Трех мерный массив A размером (5,5,3):
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]
  [39 40 41]
  [42 43 44]]

 [[45 46 47]
  [48 49 50]
  [51 52 53]
  [54 55 56]
  [57 58 59]]

 [[60 61 62]
  [63 64 65]
  [66 67 68]
  [69 70 71]
  [72 73 74]]]
Двумерный массив B размером (5,5):
 [[0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1]]
Результат перемножения массивов A и B:
 [[[0.  0.1 0.2]
  [0.3 0.4 0.5]
  [0.6 0.7 0.8]
  [0.9 1.  1.1]
  [1.2 1.3 1.4]]

 [[1.5 1.6 1.7]
  [1.8 1.9 2. ]
  [2.1 2.2 2.3]
  [2.4 2.5 2.6]
  [2.7 2.8 2.9]]

 [[3.  3.1 3.2]
  [3.3 3.4 3.5]
  [3.6 3.7 3.8]
  [3.9 4.  4.1]
  [4.2 4.3 4.4]]

 [[4.5 4.6 4.7]
  [4.8 4.9 5. ]
  [5.1 5.2 5.3]
  [5.4 5.5 5.6]
  [5.7 5.8 5.9]]

 [[6.  6.1 6.2]
  [6.3 6.4 6.5]
  [6.6 6.7 6.8]
  [6.9 7.  7.1]
  [7.2 7.3 7.4]]]


#### 36. Как вычислить средние значения, используя скользящее окно по массиву? (★★★)

In [ ]:
size_window = 2
a = np.arange(20)
cumsum_arr = np.cumsum(a)
cumsum_arr[size_window:] = cumsum_arr[size_window:] - cumsum_arr[:-size_window]
b= cumsum_arr[size_window - 1:] / size_window
print(f'Исходный вектор Z длинной {len(a)}:\n', a, '\n')
print(f'Вектор средних значений скользящего окна рамера {size_window} вектора Z:\n', b)
print(f', длина вектора ', len(b), '\n')


Исходный вектор Z длинной 20:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

Вектор средних значений скользящего окна рамера 2 вектора Z:
 [ 0.5  1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5
 14.5 15.5 16.5 17.5 18.5]
, длина вектора  19 



#### 37. Рассмотрим одномерный массив Z, постройте из него двумерный массив, первая строка которого (Z[0],Z[1],Z[2]), а каждая последующая строка сдвинута на 1 (последняя строка должна быть (Z[ -3],Z[-2],Z[-1]) (★★★)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 38. Рассмотрим 2 набора точек P0,P1, описывающих линии (2d), и набор точек P. Как вычислить расстояние от каждой точки j (P[j]) до каждой линии i (P0[i],P1[i])?(★★★)

In [ ]:
def distance_point_to_lines(d_P0, d_P1, d_point, with_pp=True):
    Len_line = d_P1 - d_P0
    L_2 = (Len_line**2).sum(axis=1)
    U = -((d_P0[:,0]-d_point[...,0])*Len_line[:,0] + (d_P0[:,1]-d_point[...,1])*Len_line[:,1]) / L_2
    U = U.reshape(len(U),1)
    points_of_perpendicular = d_P0 + U*Len_line
    D = points_of_perpendicular - d_point
    if with_pp:
        return np.sqrt((D**2).sum(axis=1)), points_of_perpendicular
    else:
        return np.sqrt((D**2).sum(axis=1))


N = 5  # количество линий и точек
P0 = np.random.randint(0, 10, (N,2))
P1 = np.random.randint(0,10,(N,2))
point = np.random.randint(0, 10, (N,2))
print('Координаты точек:\n', point)
print(f'Расстояния между точками в кол-ве ({N}) и линиями в кол-ве ({N}):\n', 
      np.array([distance_point_to_lines(P0,P1,p_i, with_pp=False) for p_i in point]))

Координаты точек:
 [[8 0]
 [0 7]
 [2 7]
 [9 9]
 [1 8]]
Расстояния между точками в кол-ве (5) и линиями в кол-ве (5):
 [[2.058  1.8974 7.6026 7.     5.3666]
 [1.2005 3.4785 2.6833 0.     4.4721]
 [0.5145 1.5811 0.8944 0.     3.5777]
 [7.5459 5.6921 4.4721 2.     2.2361]
 [0.1715 2.2136 2.2361 1.     4.9193]]


#### 39. Рассмотрим массив Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], как сгенерировать массив R = [[1,2,3, 4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
N = 15  # размер массива
Z = np.arange(N,dtype=np.int32)
print(f'Исходный массив Z размера {Z.shape[0]}:\n', Z)
def rolling_window(d_array, d_size_window):
    shape = d_array.shape[:-1] + (d_array.shape[-1] - d_size_window + 1, d_size_window)
    strides = d_array.strides + (d_array.strides[-1],)
    return stride_tricks.as_strided(d_array, shape=shape, strides=strides)

size_window = 4
roll_window = rolling_window(Z,size_window)
print(f'Искомый массив R размера {roll_window.shape[0]} на {roll_window.shape[1]} :\n', roll_window)

Исходный массив Z размера 15:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Искомый массив R размера 12 на 4 :
 [[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 40. Найдите ранг случайной матрицы (★★★)

In [ ]:
N = 10
Z = np.random.randint(2,size=(N,N))
print(f'Исходный матрица Z размера {Z.shape[0]} на {Z.shape[1]}:\n', Z)
rank = np.linalg.matrix_rank(Z, tol=1e-10)
print(f'Ранг матрицы Z:=', rank)

Исходный матрица Z размера 10 на 10:
 [[0 1 0 1 1 0 0 1 0 1]
 [0 1 1 0 1 0 1 0 1 1]
 [1 0 0 1 1 0 0 1 0 0]
 [0 1 1 0 0 0 0 0 0 1]
 [1 0 0 1 0 1 0 1 1 0]
 [1 1 1 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 0 1 0 0]
 [1 0 0 0 0 0 1 0 0 0]
 [1 1 0 0 0 1 1 1 1 0]
 [0 1 0 0 1 0 1 0 0 1]]
Ранг матрицы Z:= 10


#### 41. Как найти наиболее часто встречающееся значение в массиве?

In [ ]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[5 3 2 0 8 5 4 0 9 5 8 0 0 3 7 8 3 2 3 8 8 7 1 8 6 7 8 0 8 8 8 4 8 9 3 2 1
 7 4 3 3 7 7 0 5 6 9 7 8 6]
8


#### 42. Рассмотрим два массива A и B формы (8,3) и (2,2). Как найти строки A, содержащие элементы каждой строки B, независимо от порядка элементов в B? (★★★)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 7]


#### 43. Как извлечь уникальные значения из 2-х двумерных массивов?(★★★)

In [ ]:
Z = np.random.randint(0, 15, (4,2))
T = np.random.randint(0, 15, (4,2)) 
X = np.unique([Z,T])
print(Z,"\n",T)
print(X)


[[12  5]
 [13 13]
 [11  9]
 [11 12]] 
 [[ 5  1]
 [13  6]
 [ 5  8]
 [ 1 14]]
[ 1  5  6  8  9 11 12 13 14]
